name: fastsverl
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py311h06a4308_0
  - aiohappyeyeballs=2.4.4=py311h06a4308_0
  - aiohttp=3.11.10=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py311h06a4308_0
  - blas=1.0=mkl
  - blinker=1.9.0=py311h06a4308_0
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cachetools=5.5.1=py311h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cairocffi=1.7.1=pyhd8ed1ab_1
  - cairosvg=2.7.1=pyhd8ed1ab_1
  - certifi=2025.4.26=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py311h06a4308_0
  - cloudpickle=3.0.0=py311h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py311hdb19cb5_0
  - cryptography=41.0.3=py311h130f0dd_0
  - cssselect2=0.2.1=pyh9f0ad1d_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py311h5eee18b_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py311h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - google-auth=2.38.0=py311h06a4308_1
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.42.0=py311ha637b67_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gymnasium=0.26.3=py311h06a4308_1
  - gymnasium-notices=0.0.1=py311h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=ha637b67_0
  - libcurl=8.2.1=h91b91d3_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.7=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py311h06a4308_0
  - matplotlib=3.10.0=py311h06a4308_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - multidict=6.1.0=py311h5eee18b_0
  - mysql=5.7.24=he378463_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - oauthlib=3.2.2=py311h06a4308_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.5.5=h2aa78c0_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.0=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - ply=3.11=py311h06a4308_0
  - promise=2.3=py311h06a4308_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py311h5eee18b_0
  - protobuf=3.20.3=py311h6a678d5_0
  - psutil=5.9.0=py311h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.10.1=py311h06a4308_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pyqt6-sip=13.9.1=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h7a1cb2a_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qt-main=5.15.2=h110a718_10
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - requests-oauthlib=2.0.0=py311h06a4308_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.15.2=py311h23a989f_1
  - sentry-sdk=2.18.0=py311h06a4308_0
  - setproctitle=1.2.2=py311h5eee18b_2
  - setuptools=72.1.0=py311h06a4308_0
  - shortuuid=1.0.13=pyhd8ed1ab_1
  - sip=6.7.12=py311h6a678d5_1
  - six=1.17.0=py311h06a4308_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.6.0=py_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_1
  - tensorboard-plugin-wit=1.6.0=py_0
  - tinycss2=1.4.0=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h5eee18b_0
  - tqdm=4.67.1=py311h92b7b1e_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - urllib3=2.3.0=py311h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=py311h06a4308_1
  - werkzeug=3.1.3=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py311h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - annotated-types==0.7.0
      - docstring-parser==0.16
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - platformdirs==4.3.7
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - rich==14.0.0
      - shtab==1.7.1
      - sympy==1.13.1
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - triton==3.2.0
      - typeguard==4.4.2
      - typing-inspection==0.4.0
      - tyro==0.9.18
      - wandb==0.19.9
prefix: /home/djeb20/miniconda3/envs/fastsverl
